### ISSUE TITLE
Experimental GL 841v10: No mesh on WLAN

### ISSUE THREAD

**Issue by tuennes** [plumpudding/ffgl-firmware#1]
Config:
1043 V2 20150713stable uplink via WAN to Internet
841 V10 20151107exp mesh via WLAN 

Client via WLAN has no Internet access
841 Node is not registered on MAP

**Comment by tuennes** [comment]
If 841v10 moved to longer distance (other room):

client is connecting to uplink router (1043 V2 20150713stable)
client has Internet/freifunk access
uplink is not connected to 841

**Comment by tuennes** [comment]
:-) Client window is flickering during try to connect to webinterface

**Comment by tuennes** [comment]
no reset possible...shutdown and restart

**Comment by tuennes** [comment]
Changed config: Mesh on LAN, mesh on WLAN deactivated
see attached screenshot of statuspage
<img width="862" alt="statuspage_mesh_on_lan" src="https://cloud.githubusercontent.com/assets/15773110/11060868/33ddc832-87a3-11e5-9621-739b045feec8.png">

**Comment by tuennes** [comment]
Changed to different room:
client connected via WLAN, connection speed good, no package loss (cable)
<img width="849" alt="statuspage_mesh_on_lan_2" src="https://cloud.githubusercontent.com/assets/15773110/11061109/e94b1804-87a4-11e5-9536-b5bb8e972887.png">

**Comment by tuennes** [comment]
after gateway change (wupper3 down) connecting speed increased heavily

**Comment by tuennes** [comment]
Conclusion: No WLAN Mesh if 841v10 is trying to build mesh to uplink router
Changed config:
841 V10 20151107exp uplink to internet
1043 V2 20150713stable via Mesh on WLAN

Speed good (comparable with 1043)
No mesh on WLAN

**Comment by Marssl78** [comment]
Hello!
I offered testing the Gluon Master with support for 841v10 an fixing the TX-Power-Issue. Therefor PetaByteBoy generated a Firmware-File for me with Date 20151024 / gluon-2015.1-212-g161f430 and it was a bit tricky (for me) to get Meshing to work.

As far as i understood, this Version introduces 802.11s Meshing and uses this in standard config instead of adhoc-networking. So what I did was following:

Our Setup is one TP-Link TL-WR3600 v1 (fw 20150713stable) with VPN-Mesh on the WAN-Connection (leading to our FritzBox 3370 GuestPort) and the TP-Link TL-WR841N v10 as a "pure" Mesh-Node.

-After flashing the 841v10 it worked fine as "standalone" device with it's wan-port connected to the fritzbox "guest"-network port, but the tl-wr3600 wouldn't mesh to it. the other way round, the tl-wr3600 connected to the fritzbox worked fine as well, but the 841v10 wouldn't mesh to it, either.
-So I logged in to the routers with ssh and compared the sections concerning wireless.mesh_radio0 an discovered, that in the 841v10 the config was standard for 802.11s with type mesh instead of adhoc and several parameters that wr-3600 didn't even show an others missing. So I bravely (or foolishly) decided to delete and add and change what was different in 841v10 (channelwidth was 20 instead of 40+, and so on) and when everything was done, the 841v10 finally meshed to the wr-3600. :-)

Have a look at the map of Domain gl.wupper and see nodes CafeKroppenberg and CafeKroppenbergGarten. The second mentioned is the 841v10.

**Comment by plumpudding** [comment]
@Marssl78 you can also try the new firmware from http://gl.wupper.ffrl.de/images/
Please flash it with "sysupgrade -s". It should mesh without further changes.

**Comment by plumpudding** [comment]
I meant "sysupgrade -n"!

**Comment by tuennes** [comment]
@Marssl78 : If you activate autoupdate it will be updated to 
20151120-exp / gluon-v2015.1-262-g77829cd
This is meshing very well
@plumpudding: Many thanks!

**Comment by tuennes** [comment]
Config:
1043 V2 20150713stable uplink via WAN to Internet
 20151120exp mesh via WLAN 

good meshing and registering on map
Fast Connection Speed (Client connected to 841 V10)

**Comment by tuennes** [comment]
Still open: poor signal strength
1043 v2: max -30dbm
841 v10: max -42dbm

**Comment by KK4** [comment]
signal strength is fine for me, same as v9, but max tranfer capacity (max rate) is still dropped (same problem as with 940nV3/941NDV6) not 300/450 as it should be

**Comment by tuennes** [comment]
correct. Max rate is 156

**Comment by plumpudding** [comment]
>1043 v2: max -30dbm
>841 v10: max -42dbm

@tuennes the 1043 is a different router

>max tranfer capacity (max rate) is still dropped

which is because we were forced to drop HT40 support, which lead to a higher max rate in the last release
@KK4  did you try comparing a v9 and v10 both with the experimental

this discussion is far off topic and as the mesh works with the experimental i will close this issue now. you can open a new one if you have a different problem than dropped max rate or signal strength
